"use client";

import "./globals.css";

import dynamic from "next/dynamic";
import LazyComponent from "./LazyComponent";

const Home = dynamic(() => import("./page"), { ssr: false });
const Features = dynamic(() => import("./_components/features"), {
  ssr: false,
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Home />

        <Features />
      </body>
    </html>
  );
}
